# Country Definition
#  cty_map 目的是要建立每一個column與國家名稱的關係
CTY_MAP = {
    '全球': 'Total Export: Custom Clearance: USD',
    '新加坡': 'Export: Include Re Export: USD: Singapore (f5)',
    '越南': 'Export: Include Re Export: USD: Vietnam (f6)',
    '菲律賓': 'Export: Include Re Export: USD: Philippines (f7)',
    '馬來西亞': 'Export: Include Re Export: USD: Malaysia (f8)',
    '泰國': 'Export: Include Re Export: USD: Thailand (f9)',
    '印尼': 'Export: Include Re Export: USD: Indonesia (f10)',
    '柬埔寨': 'Export: Include Re Export: USD: Cambodia (f11)',
    '緬甸': 'Export: Include Re Export: USD: Myanmar (f12)',
    '汶萊': 'Export: Include Re Export: USD: Brunei (f13)',
    '寮國': 'Export: Include Re Export: USD: Laos (f14)',
    '印度': 'Export: Include Re Export: USD: India (f15)',
    '孟加拉': 'Export: Include Re Export: USD: Bangladesh (f16)',
    '巴基斯坦': 'Export: Include Re Export: USD: Pakistan (f17)',
    '斯里蘭卡': 'Export: Include Re Export: USD: Sri Lanka (f18)',
    '尼泊爾': 'Export: Include Re Export: USD: Nepal (f19)',
    '不丹': 'Export: Include Re Export: USD: Bhutan (f20)',
    '澳洲': 'Export: Include Re Export: USD: Australia (f82)',
    '紐西蘭': 'Export: Include Re Export: USD: New Zealand (f83)',
    '香港': 'Export: Include Re Export: USD: Hong Kong SAR (China) (f1)',
    '中國大陸': 'Export: Include Re Export: USD: Mainland China (f2)',
    '美國': 'Export: Include Re Export: USD: United States (f24)',
    '日本': 'Export: Include Re Export: USD: Japan (f26)',
    '南韓': 'Export: Include Re Export: USD: South Korea (f27)',
    '德國': 'Export: Include Re Export: USD: Germany (f38)',
    '荷蘭': 'Export: Include Re Export: USD: Netherlands (f47)',
    '中東': 'Export: Include Re Export: USD: Middle & Near East (f56)',
    '非洲': 'Export: Include Re Export: USD: Africa (f59)',
    '立陶宛': 'Export: Include Re Export: USD: Lithuania (f84)',
    '拉脫維亞': 'Export: Include Re Export: USD: Latvia (f97)',
    '愛沙尼亞': 'Export: Include Re Export: USD: Estonia (f86)',
    '沙烏地阿拉伯': 'Export: Include Re Export: USD: Saudi Arabia (f88)',
    '土耳其': 'Export: Include Re Export: USD: Turkey (f89)',
    '奈及利亞': 'Export: Include Re Export: USD: Nigeria (f91)',
    '埃及': 'Export: Include Re Export: USD: Egypt (f92)',
    '南非': 'Export: Include Re Export: USD: South Africa (f93)',
    '肯亞': 'Export: Include Re Export: USD: Kenya (f94)',
    '阿爾及利亞': 'Export: Include Re Export: USD: Algeria (f95)',
    '歐洲': 'Export: Include Re Export: USD: Europe (f96)'
}


# table2_dict, table3_part1_dict與table3_part2_dict is used to define the country sequence and define
TABLE2_DICT = {
    '全球': ['全球'],
    '新南向18國': ['新加坡', '越南', '菲律賓', '馬來西亞', '泰國', '印尼', '柬埔寨', '緬甸', '汶萊', '寮國', '印度', '孟加拉', '巴基斯坦', '斯里蘭卡', '尼泊爾', '不丹', '澳洲', '紐西蘭'],
    '東協10國': ['新加坡', '越南', '菲律賓', '馬來西亞', '泰國', '印尼', '柬埔寨', '緬甸', '汶萊', '寮國'],
    '新加坡': ['新加坡'],
    '越南': ['越南'],
    '菲律賓': ['菲律賓'],
    '馬來西亞': ['馬來西亞'],
    '泰國': ['泰國'],
    '印尼': ['印尼'],
    '柬埔寨': ['柬埔寨'],
    '緬甸': ['緬甸'],
    '汶萊': ['汶萊'],
    '寮國': ['寮國'],
    '南亞6國': ['印度', '孟加拉', '巴基斯坦', '斯里蘭卡', '尼泊爾', '不丹'],
    '印度': ['印度'],
    '孟加拉': ['孟加拉'],
    '巴基斯坦': ['巴基斯坦'],
    '斯里蘭卡': ['斯里蘭卡'],
    '尼泊爾': ['尼泊爾'],
    '不丹': ['不丹'],
    '紐澳': ['澳洲', '紐西蘭'],
    '澳洲': ['澳洲'],
    '紐西蘭': ['紐西蘭']
}

TABLE3_PART1_DICT = {
    '全球': ['全球'],
    '2021年我國主要出口市場': ["blank"],
    '中國大陸及香港': ['中國大陸', '香港'],
    '美國': ['美國'],
    '日本': ['日本'],
    '新加坡': ['新加坡'],
    '韓國': ['南韓'],
    '越南': ['越南'],
    '馬來西亞': ['馬來西亞'],
    '德國': ['德國'],
    '荷蘭': ['荷蘭'],
    '菲律賓': ['菲律賓'],
    '印度': ['印度']
}

TABLE3_PART2_DICT = {
    '全球': ['全球'],
    '歐洲': ["歐洲"],
    '立陶宛': ['立陶宛'],
    '拉脫維亞': ["拉脫維亞"],
    '愛沙尼亞': ['愛沙尼亞'],
    '中東': ['中東'],
    '沙烏地阿拉伯': ['沙烏地阿拉伯'],
    '土耳其': ['土耳其'],
    '非洲': ['非洲'],
    '奈及利亞': ['奈及利亞'],
    '埃及': ['埃及'],
    '南非': ['南非'],
    '肯亞': ['肯亞'],
    '阿爾及利亞': ['阿爾及利亞']
}

# 定義原始資料台韓日中新對各國出口所相應的欄位資訊
TAIWAN_EXPORT_DICT = {
    '全球': 'Total Export: Custom Clearance: USD (f42)',
    '中國大陸': 'Export: Include Re Export: USD: Mainland China',
    '香港': 'Export: Include Re Export: USD: Hong Kong SAR (China) (f43)',
    '美國': 'Export: Include Re Export: USD: United States',
    '日本': 'Export: Include Re Export: USD: Japan',
    '新加坡': 'Export: Include Re Export: USD: Singapore (f44)',
    '韓國': 'Export: Include Re Export: USD: South Korea',
    '越南': 'Export: Include Re Export: USD: Vietnam',
    '馬來西亞': 'Export: Include Re Export: USD: Malaysia',
    '荷蘭': 'Export: Include Re Export: USD: Netherlands',
    '德國': 'Export: Include Re Export: USD: Germany',
    '菲律賓': 'Export: Include Re Export: USD: Philippines',
    '泰國': 'Export: Include Re Export: USD: Thailand',
    '印尼': 'Export: Include Re Export: USD: Indonesia',
    '印度': 'Export: Include Re Export: USD: India',
    '中東': 'Export: Include Re Export: USD: Middle & Near East',
    '非洲': 'Export: Include Re Export: USD: Africa',
    '柬埔寨': 'Export: Include Re Export: USD: Cambodia (f45)',
    '寮國': 'Export: Include Re Export: USD: Laos (f46)',
    '緬甸': 'Export: Include Re Export: USD: Myanmar (f47)',
    '不丹': 'Export: Include Re Export: USD: Brunei (f48)',
    '土耳其': 'Export: Include Re Export: USD: Turkey',
    '沙烏地阿拉伯': 'Export: Include Re Export: USD: Saudi Arabia'
}

KOREA_EXPORT_DICT = {
    '全球': 'Exports fob (f49)',
    '中國大陸': 'Exports: Asia: China',
    '香港': 'Exports: Asia: Hong Kong SAR (China) (f51)',
    '美國': 'Exports: North America: USA',
    '日本': 'Exports: Asia: Japan',
    '新加坡': 'Exports: Asia: Singapore (f52)',
    '越南': 'Exports: Asia: Vietnam',
    '馬來西亞': 'Exports: Asia: Malaysia',
    '荷蘭': 'Exports: Europe: Netherlands (f53)',
    '德國': 'Exports: Europe: Germany',
    '菲律賓': 'Exports: Asia: Philippines',
    '泰國': 'Exports: Asia: Thailand',
    '印尼': 'Exports: Asia: Indonesia',
    '印度': 'Exports: Asia: India',
    '東協': 'Exports: ASEAN (f50)',
    '中東': 'Exports: Middle East',
    '土耳其': 'Exports: Europe: Turkey (f84)',
    '埃及': 'Exports: Middle East: Egypt (f85)',
    '非洲': 'Exports: Africa',
    '歐盟': 'Exports: Europe: EU (27)',
    '沙烏地阿拉伯': 'Exports: Middle East: Saudi Arabia'
}

JAPAN_EXPORT_DICT = {
    '全球': 'Exports (f54)',
    '中國大陸': 'Exports: China (f25)',
    '香港': 'Exports: Hong Kong SAR (China) (f57)',
    '美國': 'Exports: USA (f26)',
    '新加坡': 'Exports: Singapore (f55)',
    '韓國': 'Exports: South Korea (f37)',
    '越南': 'Exports: Vietnam (f28)',
    '馬來西亞': 'Exports: Malaysia (f30)',
    '荷蘭': 'Exports: Netherlands (f58)',
    '德國': 'Exports: Germany (f27)',
    '菲律賓': 'Exports: Philippines (f29)',
    '泰國': 'Exports: Thailand (f31)',
    '印尼': 'Exports: Indonesia (f32)',
    '印度': 'Exports: India (f33)',
    '東協': 'Exports: ASEAN (f56)',
    '中東': 'Exports: Middle East (f59)',
    '賽普勒斯': 'Exports: Cyprus (f86)',
    '土耳其': 'Exports: Turkey (f87)',
    '非洲': 'Exports: Africa (f60)',
    '歐盟': 'Exports: EU (f89)',
    '沙烏地阿拉伯': 'Exports: Saudi Arabia (f90)',
}

CHINA_EXPORT_DICT = {
    '全球': 'Exports fob: Revised',
    '美國': 'Exports: USA',
    '日本': 'Exports: Japan',
    '新加坡': 'Exports: Singapore (f61)',
    '韓國': 'Exports: South Korea',
    '越南': 'Exports: Vietnam',
    '馬來西亞': 'Exports: Malaysia',
    '荷蘭': 'Exports: Netherlands (f63)',
    '德國': 'Exports: Germany',
    '菲律賓': 'Exports: Philippines',
    '泰國': 'Exports: Thailand',
    '印尼': 'Exports: Indonesia',
    '印度': 'Exports: India',
    '東協': 'Exports: ASEAN (f62)',
    '中東': 'CN: Exports: fob: Emerging and Developing Economies: Middle East (f88)',
    '非洲': 'Exports: Africa.1',
    '歐盟': 'Exports: HS: EU',
    '沙烏地阿拉伯': 'CN: Exports: fob: Emerging and Developing Economies: Middle East, North Africa, and Pakistan: Saudi Arabia',
    '土耳其': 'CN: Exports: fob: Emerging and Developing Economies: Europe: Emerging and Developing Europe: Turkey'
}

SINGAPORT_EXPORT_DICT = {
    '全球': 'Exports (f41)',
    '中國大陸': 'Exports: China (f7)',
    '香港': 'Exports: Hong Kong SAR (China) (f64)',
    '美國': 'Exports: USA (f8)',
    '日本': 'Exports: Japan (f17)',
    '韓國': 'Exports: South Korea (f18)',
    '越南': 'Exports: Vietnam (f10)',
    '馬來西亞': 'Exports: Malaysia (f12)',
    '荷蘭': 'Exports: Netherlands (f65)',
    '德國': 'Exports: Germany (f9)',
    '菲律賓': 'Exports: Philippines (f11)',
    '泰國': 'Exports: Thailand (f13)',
    '印尼': 'Exports: Indonesia (f14)',
    '印度': 'Exports: India (f15)',
    '不丹': 'Exports: Brunei (f66)',
    '柬埔寨': 'Exports: Cambodia (f67)',
    '寮國': 'Exports: Lao Peo Dem Rep (f68)',
    '緬甸': 'Exports: Myanmar (f69)',
    '以色列': 'Exports: Israel (f70)',
    '阿拉伯聯合大公國': 'Exports: United Arab Emirates (f71)',
    '沙烏地阿拉伯': 'Exports: Saudi Arabia (f72)',
    '科威特': 'Exports: Kuwait (f73)',
    '卡達': 'Exports: Qatar (f74)',
    '黎巴嫩': 'Exports: Lebanon (f75)',
    '巴林': 'Exports: Bahrain (f76)',
    '約旦': 'Exports: Jordan (f77)',
    '阿曼': 'Exports: Oman (f78)',
    '伊朗': 'Exports: Iran (f79)',
    '敘利亞': 'Exports: Syrian Arab Rep (f80)',
    '葉門': 'Exports: Yemen (f81)',
    '賽普勒斯': 'Exports: Cyprus (f82)',
    '土耳其': 'Exports: Turkey (f83)',
    '非洲': 'Exports: Africa (f5)'
}

TABLE5_COUNTRY_ITEM_MAP = [["臺灣", TAIWAN_EXPORT_DICT],
                           ["韓國", KOREA_EXPORT_DICT],
                           ["日本", JAPAN_EXPORT_DICT],
                           ["中國大陸", CHINA_EXPORT_DICT]]


# define 臺韓日中對主要市場出口成長率比較表國家排序順序
TABLE5_COL_ITEM = {
    '全球': ['全球'],
    '2021年我國主要出口市場': ["blank"],
    '中國大陸及香港': ['中國大陸', '香港'],
    '美國': ['美國'],
    '歐盟': ['歐盟'],
    '日本': ['日本'],
    '韓國': ['韓國'],
    '越南': ['越南'],
    '馬來西亞': ['馬來西亞'],
    '泰國': ['泰國'],
    '印尼': ['印尼'],
    '菲律賓': ['菲律賓'],
    '印度': ['印度'],
    '沙烏地阿拉伯': ['沙烏地阿拉伯'],
    '土耳其': ['土耳其'],
    '非洲': ['非洲']
}
